import type { ITAsset } from "./types";

export const mockAssets: ITAsset[] = [
  {
    id: "1",
    assetTag: "AST-0001",
    name: "Dell Latitude 5540",
    type: "Laptop",
    brand: "Dell",
    model: "Latitude 5540",
    serialNumber: "DL-5540-8A3F2B",
    status: "In Use",
    assignedTo: "Juan Dela Cruz",
    location: "Main Office - Floor 1",
    department: "IT",
    purchaseDate: "2023-06-15",
    warrantyExpiry: "2026-06-15",
    purchaseCost: 1250,
    notes: "Primary workstation for IT admin",
    isDeleted: false,
  },
  {
    id: "2",
    assetTag: "AST-0002",
    name: "HP LaserJet Pro M404n",
    type: "Printer",
    brand: "HP",
    model: "LaserJet Pro M404n",
    serialNumber: "HP-M404-9C1D5E",
    status: "Active",
    assignedTo: null,
    location: "Main Office - Floor 1",
    department: "Finance",
    purchaseDate: "2022-03-10",
    warrantyExpiry: "2025-03-10",
    purchaseCost: 350,
    notes: "Shared printer for finance department",
    isDeleted: false,
  },
  {
    id: "3",
    assetTag: "AST-0003",
    name: "Lenovo ThinkPad X1 Carbon",
    type: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon Gen 11",
    serialNumber: "LN-X1C-4E7F8G",
    status: "Active",
    assignedTo: "Maria Santos",
    location: "Main Office - Floor 2",
    department: "Engineering",
    purchaseDate: "2024-01-20",
    warrantyExpiry: "2027-01-20",
    purchaseCost: 1800,
    notes: "Developer workstation",
    isDeleted: false,
  },
  {
    id: "4",
    assetTag: "AST-0004",
    name: "Dell PowerEdge R750",
    type: "Server",
    brand: "Dell",
    model: "PowerEdge R750",
    serialNumber: "DL-R750-H2I3J4",
    status: "Active",
    assignedTo: null,
    location: "Server Room A",
    department: "IT",
    purchaseDate: "2023-02-28",
    warrantyExpiry: "2028-02-28",
    purchaseCost: 12500,
    notes: "Primary application server",
    isDeleted: false,
  },
  {
    id: "5",
    assetTag: "AST-0005",
    name: "Samsung Odyssey G7 32\"",
    type: "Monitor",
    brand: "Samsung",
    model: "Odyssey G7 LC32G75T",
    serialNumber: "SM-G7-5K6L7M",
    status: "In Use",
    assignedTo: "Pedro Reyes",
    location: "Main Office - Floor 2",
    department: "Engineering",
    purchaseDate: "2023-09-05",
    warrantyExpiry: "2026-09-05",
    purchaseCost: 550,
    notes: "Design team monitor",
    isDeleted: false,
  },
  {
    id: "6",
    assetTag: "AST-0006",
    name: "Cisco Catalyst 9300",
    type: "Network Device",
    brand: "Cisco",
    model: "Catalyst 9300-48P",
    serialNumber: "CS-9300-N8O9P0",
    status: "Active",
    assignedTo: null,
    location: "Server Room A",
    department: "IT",
    purchaseDate: "2022-11-15",
    warrantyExpiry: "2027-11-15",
    purchaseCost: 8200,
    notes: "Core network switch",
    isDeleted: false,
  },
  {
    id: "7",
    assetTag: "AST-0007",
    name: "Apple MacBook Pro 14\"",
    type: "Laptop",
    brand: "Apple",
    model: "MacBook Pro M3 Pro",
    serialNumber: "AP-MBP-Q1R2S3",
    status: "Available",
    assignedTo: null,
    location: "Main Office - Floor 1",
    department: "Marketing",
    purchaseDate: "2024-03-10",
    warrantyExpiry: "2027-03-10",
    purchaseCost: 2400,
    notes: "Spare laptop for new hires",
    isDeleted: false,
  },
  {
    id: "8",
    assetTag: "AST-0008",
    name: "HP EliteDesk 800 G9",
    type: "Desktop",
    brand: "HP",
    model: "EliteDesk 800 G9",
    serialNumber: "HP-800-T4U5V6",
    status: "In Use",
    assignedTo: "Ana Garcia",
    location: "Main Office - Floor 1",
    department: "HR",
    purchaseDate: "2023-04-22",
    warrantyExpiry: "2026-04-22",
    purchaseCost: 980,
    notes: "HR department workstation",
    isDeleted: false,
  },
  {
    id: "9",
    assetTag: "AST-0009",
    name: "Brother HL-L2350DW",
    type: "Printer",
    brand: "Brother",
    model: "HL-L2350DW",
    serialNumber: "BR-L23-W7X8Y9",
    status: "Maintenance",
    assignedTo: null,
    location: "Branch Office - Cebu",
    department: "Operations",
    purchaseDate: "2021-08-12",
    warrantyExpiry: "2024-08-12",
    purchaseCost: 180,
    notes: "Paper jam issue - under repair",
    isDeleted: false,
  },
  {
    id: "10",
    assetTag: "AST-0010",
    name: "Dell UltraSharp U2723QE",
    type: "Monitor",
    brand: "Dell",
    model: "UltraSharp U2723QE 27\"",
    serialNumber: "DL-U27-Z1A2B3",
    status: "In Use",
    assignedTo: "Carlos Mendoza",
    location: "Main Office - Floor 3",
    department: "Finance",
    purchaseDate: "2023-07-18",
    warrantyExpiry: "2026-07-18",
    purchaseCost: 620,
    notes: "4K USB-C monitor for finance team",
    isDeleted: false,
  },
  {
    id: "11",
    assetTag: "AST-0011",
    name: "Lenovo ThinkCentre M70q",
    type: "Desktop",
    brand: "Lenovo",
    model: "ThinkCentre M70q Gen 3",
    serialNumber: "LN-M70-C4D5E6",
    status: "Active",
    assignedTo: "Sofia Lim",
    location: "Branch Office - Cebu",
    department: "Finance",
    purchaseDate: "2023-11-01",
    warrantyExpiry: "2026-11-01",
    purchaseCost: 750,
    notes: "Compact desktop for branch office",
    isDeleted: false,
  },
  {
    id: "12",
    assetTag: "AST-0012",
    name: "APC Smart-UPS 1500",
    type: "Server",
    brand: "APC",
    model: "Smart-UPS SMT1500",
    serialNumber: "APC-15-F7G8H9",
    status: "Active",
    assignedTo: null,
    location: "Server Room A",
    department: "IT",
    purchaseDate: "2022-06-20",
    warrantyExpiry: "2027-06-20",
    purchaseCost: 650,
    notes: "UPS for server rack A",
    isDeleted: false,
  },
  {
    id: "13",
    assetTag: "AST-0013",
    name: "Dell Latitude 7440",
    type: "Laptop",
    brand: "Dell",
    model: "Latitude 7440 Ultralight",
    serialNumber: "DL-744-I1J2K3",
    status: "Retired",
    assignedTo: null,
    location: "Warehouse",
    department: "IT",
    purchaseDate: "2020-05-10",
    warrantyExpiry: "2023-05-10",
    purchaseCost: 1600,
    notes: "Retired - battery failure, 4 years old",
    isDeleted: false,
  },
  {
    id: "14",
    assetTag: "AST-0014",
    name: "ASUS ProArt PA278QV",
    type: "Monitor",
    brand: "ASUS",
    model: "ProArt PA278QV 27\"",
    serialNumber: "AS-PA27-L4M5N6",
    status: "In Use",
    assignedTo: "Rico Tan",
    location: "Main Office - Floor 2",
    department: "Marketing",
    purchaseDate: "2023-08-15",
    warrantyExpiry: "2026-08-15",
    purchaseCost: 430,
    notes: "Color-accurate monitor for design",
    isDeleted: false,
  },
  {
    id: "15",
    assetTag: "AST-0015",
    name: "Cisco Meraki MR46",
    type: "Network Device",
    brand: "Cisco",
    model: "Meraki MR46",
    serialNumber: "CS-MR46-O7P8Q9",
    status: "Active",
    assignedTo: null,
    location: "Main Office - Floor 1",
    department: "IT",
    purchaseDate: "2023-01-10",
    warrantyExpiry: "2028-01-10",
    purchaseCost: 1100,
    notes: "WiFi 6 access point - main floor",
    isDeleted: false,
  },
  {
    id: "16",
    assetTag: "AST-0016",
    name: "HP ZBook Firefly 16 G10",
    type: "Laptop",
    brand: "HP",
    model: "ZBook Firefly 16 G10",
    serialNumber: "HP-ZBK-R1S2T3",
    status: "In Use",
    assignedTo: "Diana Bautista",
    location: "Main Office - Floor 2",
    department: "Engineering",
    purchaseDate: "2024-02-14",
    warrantyExpiry: "2027-02-14",
    purchaseCost: 2100,
    notes: "Mobile workstation for CAD work",
    isDeleted: false,
  },
  {
    id: "17",
    assetTag: "AST-0017",
    name: "Logitech Rally Camera",
    type: "Network Device",
    brand: "Logitech",
    model: "Rally Camera",
    serialNumber: "LG-RLY-U4V5W6",
    status: "Active",
    assignedTo: null,
    location: "Main Office - Floor 1",
    department: "IT",
    purchaseDate: "2023-05-22",
    warrantyExpiry: "2026-05-22",
    purchaseCost: 2900,
    notes: "Conference room A video system",
    isDeleted: false,
  },
  {
    id: "18",
    assetTag: "AST-0018",
    name: "Lenovo Tab M10 Plus",
    type: "Laptop",
    brand: "Lenovo",
    model: "Tab M10 Plus Gen 3",
    serialNumber: "LN-TAB-X7Y8Z9",
    status: "Available",
    assignedTo: null,
    location: "Main Office - Floor 1",
    department: "Operations",
    purchaseDate: "2024-04-05",
    warrantyExpiry: "2026-04-05",
    purchaseCost: 220,
    notes: "Tablet for inventory scanning",
    isDeleted: false,
  },
  {
    id: "19",
    assetTag: "AST-0019",
    name: "Dell OptiPlex 7010",
    type: "Desktop",
    brand: "Dell",
    model: "OptiPlex 7010 SFF",
    serialNumber: "DL-701-A1B2C3",
    status: "Retired",
    assignedTo: null,
    location: "Warehouse",
    department: "Operations",
    purchaseDate: "2019-11-20",
    warrantyExpiry: "2022-11-20",
    purchaseCost: 680,
    notes: "Retired - replaced with newer model",
    isDeleted: false,
  },
  {
    id: "20",
    assetTag: "AST-0020",
    name: "Epson EcoTank L3210",
    type: "Printer",
    brand: "Epson",
    model: "EcoTank L3210",
    serialNumber: "EP-L32-D4E5F6",
    status: "Active",
    assignedTo: null,
    location: "Branch Office - Cebu",
    department: "Operations",
    purchaseDate: "2023-10-08",
    warrantyExpiry: "2025-10-08",
    purchaseCost: 250,
    notes: "Ink tank printer for branch",
    isDeleted: false,
  },
  {
    id: "21",
    assetTag: "AST-0021",
    name: "Apple iMac 24\" M3",
    type: "Desktop",
    brand: "Apple",
    model: "iMac 24-inch M3",
    serialNumber: "AP-IMC-G7H8I9",
    status: "In Use",
    assignedTo: "Liza Soberano",
    location: "Main Office - Floor 3",
    department: "Marketing",
    purchaseDate: "2024-01-15",
    warrantyExpiry: "2027-01-15",
    purchaseCost: 1750,
    notes: "Creative team workstation",
    isDeleted: false,
  },
  {
    id: "22",
    assetTag: "AST-0022",
    name: "HP ProBook 450 G10",
    type: "Laptop",
    brand: "HP",
    model: "ProBook 450 G10",
    serialNumber: "HP-450-J1K2L3",
    status: "Maintenance",
    assignedTo: null,
    location: "Main Office - Floor 1",
    department: "Finance",
    purchaseDate: "2023-03-25",
    warrantyExpiry: "2026-03-25",
    purchaseCost: 890,
    notes: "Screen flickering - display replacement needed",
    isDeleted: false,
  },
  {
    id: "23",
    assetTag: "AST-0023",
    name: "Ubiquiti UniFi USW-24-POE",
    type: "Network Device",
    brand: "Ubiquiti",
    model: "UniFi USW-24-POE Gen2",
    serialNumber: "UB-USW-M4N5O6",
    status: "Active",
    assignedTo: null,
    location: "Server Room A",
    department: "IT",
    purchaseDate: "2023-07-12",
    warrantyExpiry: "2026-07-12",
    purchaseCost: 490,
    notes: "PoE switch for IP phones and APs",
    isDeleted: false,
  },
  {
    id: "24",
    assetTag: "AST-0024",
    name: "Dell Precision 5680",
    type: "Laptop",
    brand: "Dell",
    model: "Precision 5680",
    serialNumber: "DL-PR5-P7Q8R9",
    status: "Available",
    assignedTo: null,
    location: "Main Office - Floor 1",
    department: "Engineering",
    purchaseDate: "2024-05-20",
    warrantyExpiry: "2027-05-20",
    purchaseCost: 2800,
    notes: "Workstation laptop - awaiting assignment",
    isDeleted: false,
  },
  {
    id: "25",
    assetTag: "AST-0025",
    name: "LG 27UK850-W",
    type: "Monitor",
    brand: "LG",
    model: "27UK850-W 27\" 4K",
    serialNumber: "LG-27U-S1T2U3",
    status: "Retired",
    assignedTo: null,
    location: "Warehouse",
    department: "IT",
    purchaseDate: "2020-02-14",
    warrantyExpiry: "2023-02-14",
    purchaseCost: 450,
    notes: "Retired - dead pixels, out of warranty",
    isDeleted: false,
  },
  {
    id: "26",
    assetTag: "AST-0026",
    name: "Lenovo ThinkPad L14 Gen 4",
    type: "Laptop",
    brand: "Lenovo",
    model: "ThinkPad L14 Gen 4",
    serialNumber: "LN-L14-V4W5X6",
    status: "In Use",
    assignedTo: "Mark Villanueva",
    location: "Branch Office - Cebu",
    department: "Operations",
    purchaseDate: "2024-02-28",
    warrantyExpiry: "2027-02-28",
    purchaseCost: 950,
    notes: "Branch operations laptop",
    isDeleted: false,
  },
  {
    id: "27",
    assetTag: "AST-0027",
    name: "HP Color LaserJet Pro MFP M283fdw",
    type: "Printer",
    brand: "HP",
    model: "Color LaserJet Pro MFP M283fdw",
    serialNumber: "HP-M28-Y7Z8A9",
    status: "Active",
    assignedTo: null,
    location: "Main Office - Floor 2",
    department: "Marketing",
    purchaseDate: "2023-04-10",
    warrantyExpiry: "2026-04-10",
    purchaseCost: 520,
    notes: "Color multifunction for marketing",
    isDeleted: false,
  },
  {
    id: "28",
    assetTag: "AST-0028",
    name: "Dell PowerEdge T350",
    type: "Server",
    brand: "Dell",
    model: "PowerEdge T350",
    serialNumber: "DL-T35-B1C2D3",
    status: "Maintenance",
    assignedTo: null,
    location: "Server Room A",
    department: "IT",
    purchaseDate: "2022-09-18",
    warrantyExpiry: "2027-09-18",
    purchaseCost: 4500,
    notes: "RAID controller replacement in progress",
    isDeleted: false,
  },
  {
    id: "29",
    assetTag: "AST-0029",
    name: "Logitech MX Master 3S",
    type: "Network Device",
    brand: "Logitech",
    model: "MX Master 3S",
    serialNumber: "LG-MX3-E4F5G6",
    status: "Available",
    assignedTo: null,
    location: "Main Office - Floor 1",
    department: "IT",
    purchaseDate: "2024-06-01",
    warrantyExpiry: "2026-06-01",
    purchaseCost: 90,
    notes: "Wireless mouse - spare",
    isDeleted: false,
  },
  {
    id: "30",
    assetTag: "AST-0030",
    name: "Cisco Webex Room Kit Mini",
    type: "Network Device",
    brand: "Cisco",
    model: "Webex Room Kit Mini",
    serialNumber: "CS-WRK-H7I8J9",
    status: "Active",
    assignedTo: null,
    location: "Main Office - Floor 3",
    department: "IT",
    purchaseDate: "2023-12-05",
    warrantyExpiry: "2028-12-05",
    purchaseCost: 3500,
    notes: "Video conferencing for meeting room B",
    isDeleted: false,
  },
];
